### ISSUE TITLE
Issue when running within on tag push runners.

### ISSUE THREAD

**Issue by michealroberts** [ad-m/github-push-action#131]
I have the following at the top of my workflow file:

```
name: useaestrium/tag

on:
  push:
    tags:        
        - '*.*.*'
        - '[0-9]+.[0-9]+.[0-9]+'
        - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
```

And the running is triggered for a tagged runner.

However, I am seeing the following issue when attempting to push:

```
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>
```

I'm using the action as follows:

```
      # Push the updated package.json file to the repository
      - name: Push package.json version
        if: steps.check-tag.outputs.match == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_with_lease: true
```

Is there anything I am doing wrong here, or any way to fix the issue I am seeing?

**Comment by ZPascal** [comment]
Hi @michealroberts, I'm the person who implemented the force_with_lease functionality. Could you please check and post the checkout section? 

It's necessary that you set the following parameters.

```yaml
- uses: actions/checkout@v3
  with:
    ref: ${{ github.head_ref }}
    fetch-depth: 0
```
