### ISSUE TITLE
Push fails with remote rejected deny updating a hidden ref

### ISSUE THREAD

**Issue by lukasdenk** [ad-m/github-push-action#143]
When I try the first example in the README, I always get this error message:
`! [remote rejected] HEAD -> refs/pull/15/merge (deny updating a hidden ref)`

**Comment by ZPascal** [comment]
Hi @lukasdenk, could you please explain your setup and scenario?

**Comment by lukasdenk** [comment]
Thanks for the fast reply, @ZPascal. 

This is my `ci.yml`: 
```
name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access tokenn.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          ref: ${{ github.ref }}
      - name: Create local changes
        run: echo he > t.txt
      - name: Commit files
        run: |
          git add . 
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
```

This is the error message:
```
Run ad-m/github-push-action@master
  with:
    github_token: ***
    branch: refs/pull/15/merge
    github_url: https://github.com
    directory: .
Push to branch refs/pull/15/merge
Pushing to https://github.com/FEUP-MEIC-DS-[2](https://github.com/FEUP-MEIC-DS-2022-1MEIC05/dynamic-prices-backend/actions/runs/3347182291/jobs/5544886512#step:5:2)022-1MEIC05/dynamic-prices-backend.git
POST git-receive-pack (1066 bytes)
To https://github.com/FEUP-MEIC-DS-2022-1MEIC05/dynamic-prices-backend.git
 ! [remote rejected] HEAD -> refs/pull/15/merge (deny updating a hidden ref)
error: failed to push some refs to 'https://github.com/FEUP-MEIC-DS-2022-1MEIC05/dynamic-prices-backend.git'
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (node:events:[3](https://github.com/FEUP-MEIC-DS-2022-1MEIC05/dynamic-prices-backend/actions/runs/3347182291/jobs/5544886512#step:5:3)90:28)
    at maybeClose (node:internal/child_process:106[4](https://github.com/FEUP-MEIC-DS-2022-1MEIC05/dynamic-prices-backend/actions/runs/3347182291/jobs/5544886512#step:5:4):16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:[5](https://github.com/FEUP-MEIC-DS-2022-1MEIC05/dynamic-prices-backend/actions/runs/3347182291/jobs/5544886512#step:5:5)) {
  code: 1
}
Error: Invalid exit code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:10[6](https://github.com/FEUP-MEIC-DS-2022-1MEIC05/dynamic-prices-backend/actions/runs/3347182291/jobs/5544886512#step:5:6)4:[16](https://github.com/FEUP-MEIC-DS-2022-1MEIC05/dynamic-prices-backend/actions/runs/3347182291/jobs/5544886512#step:5:17))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

Thank you!
