### ISSUE TITLE
support push submodule

### ISSUE THREAD

**Issue by dimaslanjaka** [ad-m/github-push-action#152]
can this action push submodules too ?

**Comment by ZPascal** [comment]
@dimaslanjaka Do you mean to update the corresponding used version of the submodule inside the mean repository, or something like the `git push --recurse-submodules=on-demand` command?

**Comment by dimaslanjaka** [comment]
yes.

ive used `https://github.com/JamesIves/github-pages-deploy-action` with command

```yaml
- run: git submodule foreach "git commit -m \"message\""
- name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
```

push successful but, submodules not pushed to remote. when i pull got error "commit hash not in our refs".

So, `ad-m/github-push-action` is can do that ?
