### ISSUE TITLE
Push error - require is not defined in ES module scope

### ISSUE THREAD

**Issue by jiyoonlim123** [ad-m/github-push-action#157]
This is my workflow app, but it shows following errors.

```
      - name: Push changes
        if: |
          steps.docker-files-changed.outputs.any_changed == 'true' && steps.helm-files-changed.outputs.any_changed == 'false'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
```
<img width="2187" alt="image" src="https://user-images.githubusercontent.com/86942129/220495928-295b834b-aa82-401e-accf-bd8a71b7a90a.png">

**Comment by ZPascal** [comment]
Hi @jiyoonlim123, I need a bit more information from your side to further debug the case. Could you please forward the complete action file, especially the `runs-on` part? Is it a GTE instance or public GitHub? Is the repository public available?

**Comment by jiyoonlim123** [comment]
I delete some confidential code.
It is the private GitHub and I set the push permission to the GitHub token. 
```
    runs-on: [self-hosted]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          submodules: recursive
          token: ${{ secrets.ORG_PAT }}

	- name: Update and image version
        id: update-image-version-tag
        run: |
          python hooks/update_image_tag.py

      - name: Commit changed files
        run: |
          git config user.email <USEREMAIL>
          git config user.name <USERNAME>
          git add .
          git status
          git commit -m "bump version to ${{ steps.update-image-version-tag.outputs.image_name }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
```
