### ISSUE TITLE
Missing input "github_token: ${{ secrets.GITHUB_TOKEN }}".

### ISSUE THREAD

**Issue by polina-c** [ad-m/github-push-action#170]
My repo: https://github.com/flutter-chat-dev/tic_tac_toe

Error: https://github.com/flutter-chat-dev/tic_tac_toe/actions/runs/5135214398/jobs/9240329007

Workflow:

```
name: Run layerlens.

on:
  push:
    branches: [ main]

jobs:
  generate_diagrams:
    runs-on: ubuntu-latest

    steps:
    - name: clone the repo
      uses: actions/checkout@v3

    - name: install Flutter sdk
      uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
      with:
        channel: 'stable'

    - name: version
      run: dart --version

    - name: dart pub get
      run: dart pub get

    - name: generate
      run: dart run layerlens

    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git add .
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "CI: Automated layerlens push" -a | exit 0

    - name: Push changes
      if: github.ref == 'refs/heads/main'
      uses: ad-m/github-push-action@df39337088a4cf2782a73f221bbd33f90e3e091d
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

Will appreciate help!!!

**Comment by ZPascal** [comment]
I'll check that. Do you've tried it with the corresponding `ad-m/github-push-action@master` version?

**Comment by polina-c** [comment]
just checked, the same issue: https://github.com/flutter-chat-dev/tic_tac_toe/actions/runs/5135574184/jobs/9241187446

**Comment by ZPascal** [comment]
@polina-c Is force push an option?

**Comment by polina-c** [comment]
Yes, force push is allowed in the repo.
Are you saying I can force push in action? How I should update the workflow for this?

**Comment by polina-c** [comment]
@ZPascal ?

**Comment by ZPascal** [comment]
@polina-c That was just a guess whether it might work to bypass the branch protection rule. I am in the process of testing this right now. I will report when I have the results of my test.

**Comment by ZPascal** [comment]
@polina-c I've got a solution for you. You need a personal access token, it's necessary to set up the branch protection rule "Allow force pushes" to "Specify who can force push" and set up your or own user. It's also better to specify the `force_with_lease` parameter of push action to `true`.

FYI: I've tested the solution inside [this](https://github.com/ZPascal/test_origin_push_action/actions/runs/5165266723/jobs/9304678298#step:5:1) action run.

**Comment by polina-c** [comment]
Thank you! 

Can you outline exact steps in your README.md?

**Comment by ZPascal** [comment]
@polina-c Sure, I'll adjust the documentation as a follows up.

**Comment by ZPascal** [comment]
@polina-c Can we close this issue?

**Comment by polina-c** [comment]
I checked the documentation. Is it correct understanding that I am missing 'force_with_lease: true' in my script?
Let me try it.

**Comment by polina-c** [comment]
It seems personal access token is necessary. Any chance you can outline or link steps? 
There different types of access tokens in github. How exactly they should be created to make it working?

**Comment by polina-c** [comment]
In your test script dummy2 (that succeeded) still uses secrets.GITHUB_TOKEN, that is not custom access token, but is standard githib job access token.

https://github.com/ZPascal/test_origin_push_action/blob/main/.github/workflows/test.yml

Am I missing something?

**Comment by ZPascal** [comment]
Hi @polina-c,

> I checked the documentation. Is it correct understanding that I am missing 'force_with_lease: true' in my script?
Let me try it.

This relates to your case. I had the problem that it was not possible for me to push directly to the repository, and I had to use the force_with_lease option.

> It seems personal access token is necessary. Any chance you can outline or link steps?
There are [different types of access tokens in github](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens). How exactly they should be created to make it working?

Yes, that is correct, the PAT is necessary for your case. I will create documentation on how to create the token and also publish it in the documentation of the action itself as a follow-up.

> In your test script dummy2 (that succeeded) still uses secrets.GITHUB_TOKEN, that is not custom access token, but is standard githib job access token.
https://github.com/ZPascal/test_origin_push_action/blob/main/.github/workflows/test.yml
Am I missing something?

Yes, that's right, I've used the classical token to perform a checkout of the repository, but I've used the PAT for the [push](https://github.com/ZPascal/test_origin_push_action/actions/runs/5165266723/workflow#L68) itself.

If you have any further questions, please feel free to ping me.

**Comment by ZPascal** [comment]
Hi @nriss, 

it's necessary that you've specified the corresponding custom token inside [triggered](https://github.com/ansforge/IG-documentation/actions/runs/5455795460/workflow#L10) workflow file or forward it to the other action inside the other repository. The default token `${{ secrets.GITHUB_TOKEN }}` can only be used inside the triggered repository. 

It's in general necessary that you set up an custom personal access token and specify it as described in the following code sample or forward it to the executed GH Action at the end.

```
    - name: Push changes
      if: github.ref == 'refs/heads/main'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
```
