### ISSUE TITLE
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by lackhole** [ad-m/github-push-action#186]
I'm using a self-hosted unbuntu, but since around 2 weeks ago the action keeps failing. It was working fine before that.

Workflow file:
```
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ self-hosted, doxygen ]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Delete existing docs
      run: rm -rf ${{ github.workspace }}/docs/html

    - name: Re-run doxygen
      run: doxygen

    - name: Commit changes
      run: |
        git config --local user.email "noreply@visual.camp"
        git config --local user.name "vccc-docs-generator"
        git add docs/*
        git commit -a -m "Add changes"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: release
        force: true
```

Action log:
```
Run ad-m/github-push-action@master
  with:
    github_token: ***
    branch: release
    force: true
    github_url: https://github.com
    directory: .
/home/jarvis/actions-runner/public/vccc/linux-1/externals/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/jarvis/actions-runner/public/vccc/linux-1/externals/node20/bin/node)
```

System information
*  Ubuntu 18.04.5 LTS (GNU/Linux 5.4.0-146-generic x86_64)
* node: v12.18.1
* npm: 6.14.5
It will be glad if I can get some help!
