### ISSUE TITLE
Commit does not belong to any branch

### ISSUE THREAD

**Issue by eng1n88r** [ad-m/github-push-action#191]
Pushing to a protected branch from within GitHub actions succeeded but the commit is marked as not belonging to any branch. 

I have the following workflow:
```
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    ...
    - name: Setup git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

    - name: Versionize Release
      id: versionize
      run: versionize --changelog-all --exit-insignificant-commits
      continue-on-error: true

    - name: Push changes to GitHub
      if: steps.versionize.outcome == 'success'
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        tags: true
        force_with_lease: true
```

If I remove branch protection and remove `force_with_lease: true` it seems to work fine.

Here are the outcomes of the actions. This log from the action with no branch protection and removed `force_with_lease`:
```
Run ad-m/github-push-action@v0.8.0
  with:
    github_token: ***
    branch: refs/heads/main
    tags: true
    github_url: https://github.com
    directory: .
  env:
    DOTNET_ROOT: /usr/share/dotnet
Push to branch refs/heads/main
To https://github.com/my/repo.git
   d7f4784..2187bf9  HEAD -> main
 * [new tag]         v1.1.1 -> v1.1.1
```

If the branch is protected and `force_with_lease: true` is added the logs are:
```
Run ad-m/github-push-action@v0.8.0
  with:
    github_token: ***
    branch: refs/heads/main
    tags: true
    force_with_lease: true
    github_url: https://github.com
    directory: .
  env:
    DOTNET_ROOT: /usr/share/dotnet
Push to branch refs/heads/main
To https://github.com/my/repo
 * [new tag]         v1.1.5 -> v1.1.5
```

So the `.git` is missing from `To https://github.com/my/repo` and there is no range of commits `d7f4784..2187bf9  HEAD -> main`.

So when I open the release log, I see that commit is there:
![image](https://github.com/ad-m/github-push-action/assets/883804/8eef84ca-bfd4-4cee-8c45-b32439fd4390)

But when I open it I see the following:

![image](https://github.com/ad-m/github-push-action/assets/883804/4042ffa1-bf1c-41b7-bc4e-085b8caef67b)
