### ISSUE TITLE
Failed to sync with upstream repository with the help of this project.

### ISSUE THREAD

**Issue by hongyi-zhao** [ad-m/github-push-action#193]
I tried to sync with the upstream repository with the help of this project via the workflow script [here](https://github.com/hongyi-zhao/lyx/blob/master/.github/workflows/sync-with-upstream-repository.yml), but the error occurred, see [here](https://github.com/hongyi-zhao/lyx/actions/runs/7596012327/job/20689234971) for more details, as shown below:

![image](https://github.com/ad-m/github-push-action/assets/11155854/6227e270-91c1-496b-8049-8feaef044dd0)

How do you think I could fix this error?

Regards,
Zhao

**Comment by ZPascal** [comment]
> I tried to sync with the upstream repository with the help of this project via the workflow script [here](https://github.com/hongyi-zhao/lyx/blob/master/.github/workflows/sync-with-upstream-repository.yml), but the error occurred, see [here](https://github.com/hongyi-zhao/lyx/actions/runs/7596012327/job/20689234971) for more details, as shown below:
> 
> ![image](https://private-user-images.githubusercontent.com/11155854/298347227-6227e270-91c1-496b-8049-8feaef044dd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3MDMzNjUsIm5iZiI6MTcxMTcwMzA2NSwicGF0aCI6Ii8xMTE1NTg1NC8yOTgzNDcyMjctNjIyN2UyNzAtOTFjMS00OTZiLTgwNDktOGZlYWVmMDQ0ZGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA5MDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ODExYzFlYmI4NTQ0ZTM2ZTYyOTMyNzZhM2RlZjg3NzQyMGZjOWVhNTcwMjQ1MDRlOTliMzM5YWE2YzEwZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.94U_NzPKlE3e-CunKluQOoxTv2pO0SBwAKk0Cg4YVeQ)
> 
> How do you think I could fix this error?
> 
> Regards, Zhao

Hi @hongyi-zhao,
is this case still up to date? The problem is [not related](https://github.com/hongyi-zhao/lyx/actions/runs/7596012327/job/20689234971#step:5:5) to the push action in general. Is the fetched repository publicly accessible?  If the repository is not available, it is necessary to [inject](https://github.com/hongyi-zhao/lyx/actions/runs/7596012327/workflow#L25) the credentials for the repository.

**Comment by hongyi-zhao** [comment]
See below:
```shell
werner@X10DAi:~$ /usr/bin/git clone git://git.lyx.org/lyx
Cloning into 'lyx'...
remote: Enumerating objects: 504295, done.
remote: Counting objects: 100% (504295/504295), done.
^Cmote: Compressing objects:  76% (68942/90574)
```

**Comment by ZPascal** [comment]
> > Is the fetched repository publicly accessible?
> 
> See below:
> 
> ```shell
> werner@X10DAi:~$ /usr/bin/git clone git://git.lyx.org/lyx
> Cloning into 'lyx'...
> remote: Enumerating objects: 504295, done.
> remote: Counting objects: 100% (504295/504295), done.
> ^Cmote: Compressing objects:  76% (68942/90574)
> ```

Hello @hongyi-zhao,

I have a feeling that the problem is a side effect of the missing `git config --local --add safe.directory` function in your workflow file. The setting is not included by default in the [checkout action](https://github.com/hongyi-zhao/lyx/actions/runs/7596012327/workflow#L12) version `v2`. I recommend upgrading to `v3` or `v4`. It would also be helpful if you could add the `--verbose` option to this [line](https://github.com/hongyi-zhao/lyx/actions/runs/7596012327/workflow#L25).

**Comment by hongyi-zhao** [comment]
I've recreated the [workfolws](https://github.com/hongyi-zhao/lyx/commit/0b28df8809f6ad7d67d1785def4acd693f4dc4ec) based on your comments. Let's see if it can solve the problem.

**Comment by hongyi-zhao** [comment]
> I have a feeling that the problem is a side effect of the missing `git config --local --add safe.directory` function in your workflow file. The setting is not included by default in the [checkout action](https://github.com/hongyi-zhao/lyx/actions/runs/7596012327/workflow#L12) version `v2`. I recommend upgrading to `v3` or `v4`.

Based on your above comments, it seems that if I use `v3` or `v4`, the following line is unnecessary:

https://github.com/hongyi-zhao/lyx/blob/0b28df8809f6ad7d67d1785def4acd693f4dc4ec/workflows/sync-with-upstream-repository.yml#L20

But I'm not sure if I under you correctly.

**Comment by ZPascal** [comment]
> > I have a feeling that the problem is a side effect of the missing `git config --local --add safe.directory` function in your workflow file. The setting is not included by default in the [checkout action](https://github.com/hongyi-zhao/lyx/actions/runs/7596012327/workflow#L12) version `v2`. I recommend upgrading to `v3` or `v4`.
> 
> Based on your above comments, it seems that if I use `v3` or `v4`, the following line is unnecessary:
> 
> https://github.com/hongyi-zhao/lyx/blob/0b28df8809f6ad7d67d1785def4acd693f4dc4ec/workflows/sync-with-upstream-repository.yml#L20
> 
> But I'm not sure if I understand you correctly.

Yes, that is right.

**Comment by hongyi-zhao** [comment]
Ok, thank you for your confirmation, and I've updated the corresponding settings to the following:

https://github.com/hongyi-zhao/lyx/blob/fa31f7552f625ad75c6055edb09f3a4547ab53c8/workflows/sync-with-upstream-repository.yml#L17-L19

**Comment by hongyi-zhao** [comment]
Strangely, it has exceeded the preset running cycle of my workflow, but it did not run as expected.

**Comment by ZPascal** [comment]
> Strangely, it has exceeded the preset running cycle of my workflow, but it did not run as expected, as shown [here](https://github.com/hongyi-zhao/lyx/actions).

@hongyi-zhao Is the workflow possibly paused? In general, you can also trigger the workflow manually for test purposes by adding [this](https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow) adaptation to it.

**Comment by hongyi-zhao** [comment]
Thank you very much for reminding me about this. It turned out that the workflows had been put into `workflows` instead of `.github/workflows` under the root of GitHub repository. I have corrected the problem and let's see if it works as expected.

**Comment by hongyi-zhao** [comment]
It runs but still fails, as shown below, and you see [here](https://github.com/hongyi-zhao/lyx/actions/runs/8550095753/job/23426502523) for more details:

![image](https://github.com/ad-m/github-push-action/assets/11155854/774a6d45-e530-446e-880b-175066e10131)

**Comment by ZPascal** [comment]
Hi @hongyi-zhao, I think you can remove the duplicate [checkout branch step](https://github.com/hongyi-zhao/lyx/actions/runs/8550095753/workflow#L27-L28) and change the corresponding [command](https://github.com/hongyi-zhao/lyx/actions/runs/8550095753/workflow#L31) by adding the `--allow-unrelated-histories` parameter to the execution section. I think this should solve the problem.

**Comment by hongyi-zhao** [comment]
I have repaired the workflows according to your suggestion:
https://github.com/hongyi-zhao/lyx/blob/master/.github/workflows/sync-with-upstream-repository.yml

**Comment by hongyi-zhao** [comment]
[Still failed](https://github.com/hongyi-zhao/lyx/actions/runs/8565804062/job/23474452831), as shown below:

![image](https://github.com/ad-m/github-push-action/assets/11155854/8cff4a3d-1efe-4d89-8b22-d5522082e45d)

**Comment by hongyi-zhao** [comment]
I manually resolved the conflicts on my local machine, merged with the upstream, and then pushed it to my GitHub repo. Let's see if the workflow works in subsequent update runs.

**Comment by ZPascal** [comment]
Hi @hongyi-zhao,

You have some Git merge conflicts and the problem has nothing to do with the GitHub push action. 
I will try to support you to solve the case and set up a test environment on my side.

**Comment by hongyi-zhao** [comment]
It seems that the Git merge conflicts must be solved automatically in the workflow itself.

**Comment by ZPascal** [comment]
I adjusted the GH [action](https://github.com/ZPascal/lyx/edit/master/.github/workflows/sync-with-upstream-repository.yml) and was able to carry out a [successful](https://github.com/ZPascal/lyx/actions/runs/8595839249/workflow) test. I also checked the runs [here](https://github.com/hongyi-zhao/lyx/actions/runs/8595401461/job/23550043649#step:7:11) and found that you are missing authorizations for the token. You can solve this problem as [follows](https://github.com/ad-m/github-push-action?tab=readme-ov-file#requirements-and-prerequisites).

**Comment by hongyi-zhao** [comment]
Thanks again for your patient help and guidance, I finally succeeded, as shown [here](https://github.com/hongyi-zhao/lyx/actions/runs/8599860088).

**Comment by hongyi-zhao** [comment]
Although the workflow discussed here has been successful, I still have some additional questions, as shown [here](https://github.com/hongyi-zhao/lyx/commits/master/):

![image](https://github.com/ad-m/github-push-action/assets/11155854/1e9ac6c2-a82d-4cd0-913b-bfebb92a43a5)

As shown in the figure above, this method produces many additional commits. Is there a way to avoid this problem by guaranteeing that pull only if upstream does have new commits, and then no additional commits are added in the updated GitHub mirror repo?

**Comment by ZPascal** [comment]
Yes, you can use the [following](https://github.com/ZPascal/lyx/blob/master/.github/workflows/sync-with-upstream-repository.yml#L32-L42) code snipped to handle only [valid](https://github.com/ZPascal/lyx/actions/runs/8622337933) commits.

```yaml
      - name: Merge changes from upstream
        run: git merge upstream/master --allow-unrelated-histories -Xtheirs --no-edit # Ensure the upstream branch is correct

      - name: Check if push is necessary
        id: verify-changed-files
        run: |
          if [ -n "$(git status --untracked-files=no --porcelain)" ]; then
            echo "files_changed=true" >> "$GITHUB_OUTPUT";
          else
            echo "files_changed=false" >> "$GITHUB_OUTPUT";
          fi
```

**Comment by hongyi-zhao** [comment]
Then, how about the following implementation without using your `github-push-action` package and without using the temporary variable `steps.verify-changed-files.outputs.files_changed`?

```yaml
name: Sync with upstream repository

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours, can be adjusted as needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup git
        run: |
          git config user.name "Hongyi Zhao"
          git config user.email "hongyi.zhao@gmail.com"

      - name: Add remote upstream
        run: git remote add upstream git://git.lyx.org/lyx

      - name: Fetch changes from upstream
        run: git fetch upstream

      - name: Merge changes from upstream
        run: git merge upstream/master --allow-unrelated-histories -Xtheirs --no-edit

      - name: Push changes if necessary
        run: |
          if git diff --quiet; then
            echo "No changes to push."
          else
            git push origin master
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
