### ISSUE TITLE
Subfolder uploaded to the main folder of the project instead of the dir path indicated under 'Directory' input

### ISSUE THREAD

**Issue by matteemol** [ad-m/github-push-action#199]
I'm trying to commit some files and folders to a subfolder of my main project, but all the documents end up in a pull request in the wrong location.
In some part of my workflow, I have this output:
![image](https://github.com/ad-m/github-push-action/assets/105395194/5928905b-6da7-4976-bc91-b6ac12237239)

Then, the commit & push part of the script shows the following:
![image](https://github.com/ad-m/github-push-action/assets/105395194/51523158-98dd-4f33-8c4f-327b09d3ec90)

This is the last part of the workflow script that I'm running:
![image](https://github.com/ad-m/github-push-action/assets/105395194/ec8d523a-ca1a-47fb-a111-63a5c3034447)

When I try to make the pull request, I see that all the files were pushed to the base directory instead of the expected /docs/build/html stated in the 'Directory' input:
![image](https://github.com/ad-m/github-push-action/assets/105395194/e80914a4-eeab-4a0b-b94c-a63239896130)

Am I doing something wrong?

Thanks in advance!

repository: [https://github.com/matteemol/dbSketcher](https://github.com/matteemol/dbSketcher)
workflow file: [https://github.com/matteemol/dbSketcher/blob/main/.github/workflows/commit-doc-changes.yml](https://github.com/matteemol/dbSketcher/blob/main/.github/workflows/commit-doc-changes.yml)

Edit: updated the links

**Comment by ZPascal** [comment]
Hello @matteemol, 

I have checked your workflow file and found some possible optimizations. I have the feeling that the files are already being created in the wrong directory and am setting up a test case on my end.

Regards,

Pascal

**Comment by matteemol** [comment]
Thanks @ZPascal , the workflow it's kind of a Frankenstein creation, so it's probably not the best.

I tried to follow the directives in the docs for the action in this repo, and I felt like I was doing it ok, so I opened the issue.

Although, I'm possibly 'dividing by zero' somewhere, so this issue might just be something that I'm doing wrong.

If that's the case, sorry to bother

**Comment by ZPascal** [comment]
> Thanks @ZPascal , the workflow it's kind of a Frankenstein creation, so it's probably not the best.

We can handle it together to get the expected result.

> I tried to follow the directives in the docs for the action in this repo, and I felt like I was doing it ok, so I opened the issue.
> Although, I'm possibly 'dividing by zero' somewhere, so this issue might just be something that I'm doing wrong.
> If that's the case, sorry to bother

No, problem. I'll support you.

I've opened a [PR](https://github.com/matteemol/dbSketcher/pull/1/files) and adjusted the corresponding GH action. I hope I understand you correctly and it matches your required case.

```yml
name: Commit documentation changes

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
 
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: make the sphinx docs
        run: |
          make -C docs clean 
          # sphinx-apidoc -f -o docs/source . -H Test -e -t docs/source/_templates
          make -C docs html

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/build/html/
          touch .nojekyll
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: rtd-pages
          force_with_lease: true
```

I have adjusted the folder configuration as you are pushing **from** this folder to a **new branch** and this leads to the corresponding case on your side.
