### ISSUE TITLE
Extra commit when commiting

### ISSUE THREAD

**Issue by estensen** [ad-m/github-push-action#20]
I'm trying to create a workflow that generates a file and then commits this file. This should happen on a separate branch and be merged when the action is complete. I currently use another action to merge and delete the branch.

workflow.yaml
```
    - name: Add changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add pipeline" -a

    - name: Commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.HEAD_REF }}

    - name: Merge and delete branch
      uses: estensen/auto_merge_my_pull_requests@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

When I specify `branch: ${{ github.HEAD_REF }}` [an extra commit is created](https://github.com/estensen/python-actions/pull/23) where some merging is done. When I specify `branch: ${{ github.BRANCH }}` [the branch is merged and then the commit is applied](https://github.com/estensen/python-actions/pull/25). Overview [here](https://github.com/estensen/python-actions/network).

<img width="251" alt="Screenshot 2019-10-17 at 11 49 49" src="https://user-images.githubusercontent.com/9142800/66998295-49004c00-f0d4-11e9-85e9-734fe75785f1.png">

Is it possible to have the commit happen on the branch without creating the extra merge commit?

**Comment by kenorb** [comment]
I think I've got the same issue.
![image](https://user-images.githubusercontent.com/266306/87323896-47f73080-c527-11ea-8560-692f0f6a6058.png)

My configuration is like:

```
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          # Otherwise, you will failed to push refs to dest repo.
          fetch-depth: 0
          ref: refs/heads/${{ github.head_ref }}
      - uses: actions/download-artifact@v2
         name: MyArtifact
      - name: Commit files
        run: |
          git config --local core.autocrlf false
          git config --local user.email $git_email
          git config --local user.name "${{ github.actor }}"
          git add . && git add --renormalize .
          git pull origin "${{ github.ref }}" --autostash --rebase -Xours
          git commit -am "${{ github.workflow }}"
        env:
          git_email: "${{ github.actor }}@users.noreply.github.com"
      - name: Push changes (not PR)
        if: github.event_name != 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes (PR)
        if: github.event_name == 'pull_request'
        uses: ad-m/github-push-action@master
        with:
          branch: refs/heads/${{ github.head_ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by kenorb** [comment]
Related: https://github.com/actions/checkout/issues/299

**Comment by murilogok** [comment]
Solved this issue **_(deny updating a hidden ref)_** with:

```
     with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }} <---- Add this
        force: true
```
