### ISSUE TITLE
remote: Permission to myself/myself.github.io.git denied to github-actions[bot]

### ISSUE THREAD

**Issue by jlk-inxl** [ad-m/github-push-action#201]
**Error in publishing generated content to GitHub Pages**

```
Run JamesIves/github-pages-deploy-action@4.1.4
  with:
    branch: gh-pages
    folder: public
    token: ***
    clean: true

    GitHub Pages Deploy Action 🚀

    🚀 Getting Started Guide: https://github.com/marketplace/actions/deploy-to-github-pages
    ❓ Discussions / Q&A: https://github.com/JamesIves/github-pages-deploy-action/discussions
    🔧 Report a Bug: https://github.com/JamesIves/github-pages-deploy-action/issues

    📣 Maintained by James Ives: https://jamesiv.es
    💖 Support: https://github.com/sponsors/JamesIves
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config user.name myself
/usr/bin/git config user.email 69201541+myself@users.noreply.github.com
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
Unable to unset previous git config authentication as it may not exist, continuing…
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/myself/myself.github.io.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/myself/myself.github.io.git refs/heads/gh-pages
Creating worktree…
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
Preparing worktree (detached HEAD 5c31a3a)
/usr/bin/git checkout --orphan gh-pages
Switched to a new branch 'gh-pages'
Created the gh-pages branch… 🔧
/usr/bin/git reset --hard
/usr/bin/git commit --no-verify --allow-empty -m Initial gh-pages commit
[gh-pages (root-commit) e422375] Initial gh-pages commit
/usr/bin/rsync -q -av --checksum --progress /home/runner/work/myself.github.io/myself.github.io/public/. github-pages-deploy-action-temp-deployment-folder --delete --exclude CNAME --exclude .nojekyll --exclude .ssh --exclude .git --exclude .github
Checking if there are files to commit…
/usr/bin/git add --all .
/usr/bin/git checkout -b github-pages-deploy-action/5l2z863qs
Switched to a new branch 'github-pages-deploy-action/5l2z863qs'
/usr/bin/git commit -m Deploying to gh-pages from @ myself/myself.github.io@5c31a3a6a6c5f5157d94ca04e44c7b2e69846f5f 🚀 --quiet --no-verify
/usr/bin/git push --force ***github.com/myself/myself.github.io.git github-pages-deploy-action/5l2z863qs:gh-pages
remote: Permission to myself/myself.github.io.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/myself/myself.github.io.git/': The requested URL returned error: 403
```

My publish.yml file : 

```
name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes

      - name: Build the site
        run: ./build.sh

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public
```

The token I use has all the rights.

Regarding the repo: I allowed all actions and reusable workflows 
Regarding the Workflow permissions: I gave Read and write permissions
