### ISSUE TITLE
Not all changes are being pushed

### ISSUE THREAD

**Issue by acoop133** [ad-m/github-push-action#39]
```
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Commit changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
```

this only committed a file content change and ignored a new file that was added.

![image](https://user-images.githubusercontent.com/19627023/70281976-4eb10e80-17b4-11ea-8425-db4feaf74d38.png)

https://github.com/DarkThemeHub/GithubDarkTheme/pull/114/commits/1a28d39044c8e019dfef9aff48720c15f5648ae2
