### ISSUE TITLE
How to correctly set token

### ISSUE THREAD

**Issue by yammyxing** [ad-m/github-push-action#41]
I'd like to push to my another repo

My action looks like this below:
```
...
- name: Commit files
      working-directory: ./dist
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "update blog" -a
    - name: Push changes as deploy
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PUSH_SECRET_FOR_ACTION }}
        force: true
        repository: "me.github.io"
```
And my repo's secret looks like this which value is from Personal Access Token:
![image](https://user-images.githubusercontent.com/23147304/71552930-a142bb00-2a40-11ea-8150-b587620bb642.png)

But finally Got this:
![image](https://user-images.githubusercontent.com/23147304/71552881-bc60fb00-2a3f-11ea-83ea-318f7c8904c3.png)

I've also read this related issue about [How to set GITHUB_TOKEN](https://github.com/ad-m/github-push-action/issues/23)

But I still failed. Is there sth I've been misunderstanding ? Hope to get an answer, thanks.

**Comment by ad-m** [comment]
Let's try following:
```
    - name: Push changes as deploy
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.push_secret_for_action }}
        force: true
        repository: "me.github.io"
```
