### ISSUE TITLE
Push issue

### ISSUE THREAD

**Issue by Sabuto** [ad-m/github-push-action#44]
Ok, I may be being really dumb here but

![image](https://user-images.githubusercontent.com/4526905/73374717-946ced80-42b2-11ea-9e34-0418e311f3f6.png)

I get permission denied

my workflow file:
```yaml
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Main Checkout

    - uses: actions/checkout@v2
      name: Secondary Checkout
      with:
        repository: sabuto/bot-test2
        path: bot-test2

    - name: move file to other repo
      run: \cp -Rv .github/sabubot.yml bot-test2/.github/sabubot.yml

    - name: commit to local
      run: |
        cd bot-test2
        git config --local user.email "robe_dunne@hotmail.com"
        git config --local user.name "sabuto"
        git add .
        git commit -m "Add changes"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_PSA }}
        repository: sabuto/bot-test2
```

I have the psa key setup in the repo that is triggering the workflow 
![image](https://user-images.githubusercontent.com/4526905/73374812-c2523200-42b2-11ea-971b-512b5d51d391.png)

which is a personal access token with all rights.

**Comment by robot-o** [comment]
i'm having the same issue

**Comment by magodo** [comment]
For anyone suffering this issue, this might be the `actions/checkout@v2` to blame. I have filed an [issue](https://github.com/actions/checkout/issues/148) for that.

On the other hand, I have two work arounds for this:

1. In between running checkout and push jobs, run command: `git config --unset http.https://github.com/.extraheader`
2. In checkout job, use your personal token as `token`. Then in push job, put whatever stuff to `github_token`.

**Comment by Sabuto** [comment]
@magodo  Thanks for this, I am now getting 

```bash
Started: bash /home/runner/work/_actions/ad-m/github-push-action/master/start.sh
 ! [rejected]        HEAD -> master (fetch first)
Push to branch master
error: failed to push some refs to '***github.com/sabuto/bot-test2.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
```

This makes no sense as i have pulled the latest version when i run the workflow, any ideas?

**Comment by ad-m** [comment]
@Sabuto , add ```force: true```, but you should understand what that message mean in Git due risk of data loss.

**Comment by magodo** [comment]
Are you sure you set the fetch-depth to 0? I have this issue because of that.

**Comment by Sabuto** [comment]
Thanks for this guys! and thanks for the fast responses :) i am happy for this to be closed as it works for me but will let you decide as the other haven't commented.

**Comment by organizejs** [comment]
I am unable to set `persist-credentials` and `fetch-depth` as parameters under checkout. 

I'm setting it like so:
```
    - uses: actions/checkout@master
      persist-credentials: false
      fetch-depth: 0
```

i get this error:
```
- Your workflow file was invalid: The pipeline is not valid. .github/workflows/update.yml (Line: 17, Col: 7): Unexpected value 'persist-credentials',.github/workflows/update.yml (Line: 18, Col: 7): Unexpected value 'fetch-depth'
```

**Comment by ad-m** [comment]
@organizejs , missing ```with```. Let's try:

```yaml
    - uses: actions/checkout@master
      with:
         persist-credentials: false
         fetch-depth: 0
```
