### ISSUE TITLE
Action fails if branch does not exist

### ISSUE THREAD

**Issue by psychemedia** [ad-m/github-push-action#48]
The action seems to fail if a pushed to branch does not already exist?

It would be useful if the branch was created in such a case.

**Comment by vadi2** [comment]
Confirmed. For the time being, this prerequisite works:

```
    - name: create texts branch
      uses: peterjgrainger/action-create-branch@v1.0.0
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: updated-text-for-translation
```
