### ISSUE TITLE
Not working on Mac

### ISSUE THREAD

**Issue by tofi86** [ad-m/github-push-action#51]
I'm running a build on Mac OS and try to push changes back with the following config:

```
jobs:
  release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    ...

    - name: Set up GitHub Actions git user
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: do changes
      run: ...

    - name: Push maven-release-plugin changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        tags: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

However, this results in an error:

```
Push maven-release-plugin changes

Run ad-m/github-push-action@v0.5.0
  with:
    tags: true
    github_token: ***
    branch: master
    directory: .
  env:
    JAVA_HOME: /Users/runner/hostedtoolcache/jdk/8.0.242/x64
    JAVA_HOME_8.0.242_x64: /Users/runner/hostedtoolcache/jdk/8.0.242/x64
##[error]Container action is only supported on Linux
```

Why is it not supported on Mac OS? Does anyone have a workaround for that?

Thanks for your help and all the best,
Tobias
