### ISSUE TITLE
Push issue, 403 error

### ISSUE THREAD

**Issue by slinden2** [ad-m/github-push-action#55]
Out of the blue today my workflow stopped working at push to repo step. 

It gives me the following error:

```
Run ad-m/github-push-action@master
Started: bash /home/runner/work/_actions/ad-m/github-push-action/master/start.sh
Push to branch master
remote: Permission to ***/sunday-night-wreckfest.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/***/sunday-night-wreckfest.git/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

I have use the same workflow without changes for a couple of weeks and today I suddenly started encountering this problem.

Here's also my workflow:

```
name: Test and Deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory-be: ./backend
      working-directory-fe: ./frontend
      GS_PRIVATE_KEY: ${{ secrets.GS_PRIVATE_KEY }}
      GS_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GS_SERVICE_ACCOUNT_EMAIL }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install backend dependencies
        run: npm install
        working-directory: ${{ env.working-directory-be }}
      - name: Run tests
        run: npm test
        working-directory: ${{ env.working-directory-be }}
        env:
          CI: true
      - name: Build backend
        run: npm run build:server
        working-directory: ${{ env.working-directory-be }}
      - name: Install frontend dependencies
        run: npm install
        working-directory: ${{ env.working-directory-fe }}
      - name: Build frontend
        run: npm run build
        working-directory: ${{ env.working-directory-fe }}
      - name: Create production bundle
        run: |
          mkdir -p ./dist
          cp -r ./backend/build/. ./dist
          cp -r ./frontend/build/. ./dist/client
          rm -r ./backend/build/
          rm -r ./frontend/build/
          cp ./backend/package.json ./dist/package.json
          cp ./backend/package-lock.json ./dist/package-lock.json
          cp ./backend/Procfile ./dist/Procfile
      - name: Commit production bundle
        run: |
          git config --global user.name '${{ secrets.USERNAME }}'
          git config --global user.email '${{ secrets.USERNAME }}@users.noreply.github.com'
          git add .
          git commit -m "Automated production bundle creation"
      - name: Push production bundle to repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Push production bundle to dokku
        uses: slinden2/dokku-deploy-github-action@v1.1-alpha
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-ip-address: ${{ secrets.SERVER_IP }}
          dokku-host: ***
          app-name: ***
          git-subtree-prefix: "dist"
          force-push-subtree: "true"

```
