### ISSUE TITLE
Consider renaming input from 'github_token' to 'github-token'?

### ISSUE THREAD

**Issue by matthewfeickert** [ad-m/github-push-action#56]
Hi! Today I was trying to play around with some updates using `github-push-action` and I noticed I was getting the error:

```
##[warning]Unexpected input 'github-token', valid inputs are ['github_token', 'repository', 'branch', 'force', 'tags', 'directory']
```

I was quite confused by this until I read closer and noticed that I had used `github-token` in

```yaml
- name: Push changes
  uses: ad-m/github-push-action@v0.6.0
  with:
    github-token: ${{ secrets.GITHUB_TOKEN }}
```

**instead** of `github_token`

```yaml
- name: Push changes
  uses: ad-m/github-push-action@v0.6.0
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
```

As the [GitHub `github-script` action](https://github.com/actions/github-script) uses `github-token`, would you consider changing the input to match them? My library is probably not the only one that uses both `github-script` and `github-push-action` so it would probably lead to less typos and errors. If there was a reason that you intentionally chose to _not_ copy them then my apologies for missing this.

I also just wanted to say thank you, as your GitHub Action is _awesome_ and we use it quite heavily in our publication workflow for our library [`pyhf`](https://github.com/scikit-hep/pyhf/).
