### ISSUE TITLE
Error: Invalid status code: 128

### ISSUE THREAD

**Issue by matmu** [ad-m/github-push-action#58]
My action

```
    - name: Push changes to MouseFM-Backend
      uses: ad-m/github-push-action@master
      with:
        repository: matmu/MouseFM-Backend
        directory: MouseFM-Backend
        github_token: ${{ secrets.DEPLOY_PRIVATE_KEY }}
```

results in an error. The directory, secrets.DEPLOY_PRIVATE_KEY and the repository exists. What is wrong?

```
Run ad-m/github-push-action@master
Started: bash /home/runner/work/_actions/ad-m/github-push-action/master/start.sh
Push to branch master
warning: url contains a newline in its host component: https://matmu:***
***
***
***
***
***
***
***
***
***
@github.com/matmu/MouseFM-Backend.git/
fatal: credential url cannot be parsed: https://matmu:***
***
***
***
***
***
***
***
***
@github.com/matmu/MouseFM-Backend.git/
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

```
