### ISSUE TITLE
Offer a major version tag (v0)

### ISSUE THREAD

**Issue by jasongitmail** [ad-m/github-push-action#65]
Thanks for creating the action. 

The ReadMe suggests using `@master` for the version, but that's a bit risky stability wise for users. Offering a major version tag would provide stability for users, assuming you follow semver.

You can accomplish this on each release with:
```
git tag v0.7.0
git push origin v0.7.0
git tag -fa v0 -m "Update v0 tag"
git push origin v0 --force
```

Then the README could say:
```
- name: Push changes
  uses: ad-m/github-push-action@v0
  with:
     github_token: ${{ secrets.GITHUB_TOKEN }}
```
