### ISSUE TITLE
Default branch should be "main" not "master"

### ISSUE THREAD

**Issue by juancpineda97** [ad-m/github-push-action#68]
Due to the latest changes to Github, the default branches are now called "main" and not "master". Therefore, the default branch should be "main".

**Comment by ouuan** [comment]
Why not use `${{ github.ref }}` as default? (Another breaking change, though.)

**Comment by counter2015** [comment]
It's strange when I see my workflow failed due to this reason.
Since it's a break strange, why not update another version of workflow instread of modifying it directly？

**Comment by ad-m** [comment]
@counter2015 , there is no release yet and there is no updates of already released version. Use latest version. `master` detect branch automatically and should not raise issues like that.

**Comment by counter2015** [comment]
> @counter2015 , there is no release yet and there is no updates of already released version. Use latest version. `master` detect branch automatically and should not raise issues like that.

@ad-m I'm not sure, you mean  that this issue is fixed in master version?

I didn't specify version, and the `ad-m/github-push-action@master` version like following:
```
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

I fixed it by following steps
- delete `main` branch 
- use `github.ref` in config
- trigger wrokflow manually by `on: workflow_dispatch`

```
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
 ```
