### ISSUE TITLE
Facing issues while pushing to master 

### ISSUE THREAD

**Issue by yrsurya** [ad-m/github-push-action#71]
! [remote rejected] master -> master (refusing to allow a GitHub App to create or update workflow `.github/workflows/build.yml` without `workflows` permission)

using PAT keys where enabled workflow but still seeing this issue
Any Help would be appreciated

**Comment by ad-m** [comment]
Please provide your workflow file.

**Comment by yrsurya** [comment]
`name: Setup New Repository

on:
  push:
    branches: [master]

jobs:
  setup-repo-from-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with: { node-version: '14', registry-url: `'xxxxx'` }
      - env: { NODE_AUTH_TOKEN: "${{ secrets.JFROG_NPM_PUBLISH_AUTH }}" }
        run: chmod a+x ./init.sh && ./init.sh
      - name: Commit files
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          git add .
          git status
          git commit -a -m "Initialize new repository from template"
          git push https://${{ secrets.GH_TOKEN_TEST }}@github.com/org/repoi.git
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN_TEST }}
          branch: ${{ github.ref }}`

**Comment by ad-m** [comment]
Let's try:
```

on:
  push:
    branches: [master]

jobs:
  setup-repo-from-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2-beta
        with: { node-version: '14', registry-url: `'xxxxx'` }
      - env: { NODE_AUTH_TOKEN: "${{ secrets.JFROG_NPM_PUBLISH_AUTH }}" }
        run: chmod a+x ./init.sh && ./init.sh
      - name: Commit files
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          git add .
          git status
          git commit -a -m "Initialize new repository from template"
          git push https://${{ secrets.GH_TOKEN_TEST }}@github.com/org/repoi.git
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN_TEST }}
          branch: ${{ github.ref }}
```
