### ISSUE TITLE
push issue

### ISSUE THREAD

**Issue by DanielFatkic** [ad-m/github-push-action#8]
Hi,
I can't get this working and I'm not sure why.

I'm using php cs fixer to change the code and then I want to push the changes, but I'm getting following error:

> Push to branch master
>fatal: remote origin already exists.
>Everything up-to-date

My workflow:

```
on: push
name: Main
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --diff
    - name: commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: .
```

**Comment by ad-m** [comment]
You must create commit yourself eg.:
```yaml
on: push
name: Main
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --diff
    - run: git commit -m "Update" -a
    - name: commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        directory: .
```

See following diagram:
![obraz](https://user-images.githubusercontent.com/3618479/66276162-76592880-e890-11e9-914a-86319d83c7c1.png)
