### ISSUE TITLE
Push to organization repo fails with 403

### ISSUE THREAD

**Issue by F43nd1r** [ad-m/github-push-action#85]
I'm trying to push my javadoc to a different repository owned by an organization. Here's my workflow
```yaml
name: upload-javadoc

on:
  push:
    tags:
      - 'acra-*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Checkout acra
        uses: actions/checkout@v2
        with:
          path: 'main'
          persist-credentials: false
          fetch-depth: 0
      - name: Checkout github pages
        uses: actions/checkout@v2
        with:
          repository: 'ACRA/acra.github.com'
          path: 'web'
          persist-credentials: false
          fetch-depth: 0
      - name: Generate Javadoc
        run: ./gradlew dokkaHtmlCollector --no-daemon
        working-directory: ./main
      - name: Extract version
        id: version
        run: echo "::set-output name=value::$(./gradlew version --no-daemon --quiet --console=plain)"
        working-directory: ./main
      - name: Update Javadoc
        run: |
          mkdir ./web/javadoc/${{ steps.version.outputs.value }}
          cp -a ./main/build/dokka/htmlCollector/. ./web/javadoc/${{ steps.version.outputs.value }}/
          echo  "- [${{ steps.version.outputs.value }}](${{ steps.version.outputs.value }}/acra)" >> ./web/javadoc/index.md
          ln -sfn "${{ steps.version.outputs.value }}/" ./web/javadoc/latest
      - name: Commit files
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "Add javadoc for version ${{ steps.version.outputs.value }}" -a
        working-directory: ./web
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          repository: 'ACRA/acra.github.com'
          directory: ./web
```
And this is what happens:
```
Run ad-m/github-push-action@master
Push to branch master
remote: Permission to ACRA/acra.github.com.git denied to F43nd1r.
fatal: unable to access 'https://github.com/ACRA/acra.github.com.git/': The requested URL returned error: 403
Error: Invalid exit code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid exit code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:29:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

I'm not sure what I'm doing wrong. I added  `persist-credentials: false` and  `fetch-depth: 0` to both checkouts as is mentioned in other issues, but that didn't help. How can I fix this build?
